apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redirect-check-backend
spec:
  replicas: 1
  template:
    metadata:
      name: redirect-check-backend
      labels:
        app: redirect-check-backend
        role: backend
        env: production
    spec:
      containers:
      - name: redirect-check-backend
#Image tag is changed by Jenkins during build
        image: <IMAGE_TAG_DO_NOT_EDIT>
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        ports:
        - name: frontend
          containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: redirect-check-backend-service
spec:
#  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: redirect-check-backend
    role: backend
